# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df95544004aa979e255672838ae56475c3c32dfd8c1857ec77c0f863bc30af224a53efb5a98d4e88d6eb8ae039d813b8c121cf5220b62d333cd68cfd60ade70

test:
  secret_key_base: 331571a722125d319880674565043ca71c1b6c5940d88b58bab28bb26bcdc656f96e7af8f845cd6b7041566b5c300e13fb0412afac629166bfb6b1a5f6291f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
